# Generated by Django 6.0.2 on 2026-02-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_status_to_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
